In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_train = pd.read_csv('files/Analytics Vidya/train_loan_prediction.csv')
df_test = pd.read_csv('files/Analytics Vidya/test_loan_prediction.csv')
sample = pd.read_csv('files/Analytics Vidya/sample_loan_prediction.csv')

In [3]:
df_train.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [4]:
sample.head()

Loan_ID Loan_Status
0  LP001015           N
1  LP001022           N
2  LP001031           N
3  LP001035           N
4  LP001051           N

In [5]:
df_test.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             NaN         Urban  
4             1.0         Urban

In [6]:
df_train.shape

(614, 13)

In [7]:
df_test.Property_Area.unique()

array(['Urban', 'Semiurban', 'Rural'], dtype=object)

In [8]:
df_train.Credit_History.unique()

array([ 1.,  0., nan])

In [9]:
df_train = df_train.drop(columns='Loan_ID')

In [10]:
df_train.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [11]:
from sklearn_pandas import CategoricalImputer
imputer =CategoricalImputer()
df_train['Gender'] = imputer.fit_transform(df_train['Gender'])
df_train['Married'] = imputer.fit_transform(df_train['Married'])
df_train['Dependents'] = imputer.fit_transform(df_train['Dependents'])
df_train['Self_Employed'] = imputer.fit_transform(df_train['Self_Employed'])
df_train['LoanAmount'] = imputer.fit_transform(df_train['LoanAmount'])
df_train['Loan_Amount_Term'] = imputer.fit_transform(df_train['Loan_Amount_Term'])
df_train['Credit_History'] = imputer.fit_transform(df_train['Credit_History'])
print(df_train)

     Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0      Male      No          0      Graduate            No             5849   
1      Male     Yes          1      Graduate            No             4583   
2      Male     Yes          0      Graduate           Yes             3000   
3      Male     Yes          0  Not Graduate            No             2583   
4      Male      No          0      Graduate            No             6000   
..      ...     ...        ...           ...           ...              ...   
609  Female      No          0      Graduate            No             2900   
610    Male     Yes         3+      Graduate            No             4106   
611    Male     Yes          1      Graduate            No             8072   
612    Male     Yes          2      Graduate            No             7583   
613  Female      No          0      Graduate           Yes             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Ter

In [12]:
df_train.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [13]:
df_train.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male      No          0      Graduate            No             5849   
1   Male     Yes          1      Graduate            No             4583   
2   Male     Yes          0      Graduate           Yes             3000   
3   Male     Yes          0  Not Graduate            No             2583   
4   Male      No          0      Graduate            No             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0       120.0             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

  Property_Area Loan_Status  
0         Urban           Y  
1         Rural           N  
2         Urban           Y  
3         Urban           Y  
4         Urban           Y

In [13]:
x = df_train.iloc[:,-1].values
y = df_train.iloc[-1].values

In [14]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
def MultiLabelEncoder(columnList, df):
    for column in columnList:
        label_encoder = LabelEncoder()
        df[column] = label_encoder.fit_transform(df[column])

In [15]:
MultiLabelEncoder(['Gender','Married', 'Education', 'Self_Employed', 'Property_Area'], df_train)

In [16]:
df_train

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
0         1        0          0          0              0             5849   
1         1        1          1          0              0             4583   
2         1        1          0          0              1             3000   
3         1        1          0          1              0             2583   
4         1        0          0          0              0             6000   
..      ...      ...        ...        ...            ...              ...   
609       0        0          0          0              0             2900   
610       1        1         3+          0              0             4106   
611       1        1          1          0              0             8072   
612       1        1          2          0              0             7583   
613       0        0          0          0              1             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0       120.0             360.0             1.0   
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0        71.0             360.0             1.0   
610                0.0        40.0             180.0             1.0   
611              240.0       253.0             360.0             1.0   
612                0.0       187.0             360.0             1.0   
613                0.0       133.0             360.0             0.0   

     Property_Area Loan_Status  
0                2           Y  
1                0           N  
2                2           Y  
3                2           Y  
4                2           Y  
..             ...         ...  
609              0           Y  
610              0           Y  
611              2           Y  
612              2           Y  
613              1           N  

[614 rows x 12 columns]

In [17]:
df_train.Dependents.unique()

array(['0', '1', '2', '3+'], dtype=object)

In [18]:
df_train.Dependents = df_train.Dependents.replace({"3+": "3"})

In [19]:
x = df_train.iloc[:,:-1].values
y = df_train.iloc[:,-1].values

In [20]:
y.shape

(614,)

In [21]:
x

array([[1, 0, '0', ..., 360.0, 1.0, 2],
       [1, 1, '1', ..., 360.0, 1.0, 0],
       [1, 1, '0', ..., 360.0, 1.0, 2],
       ...,
       [1, 1, '1', ..., 360.0, 1.0, 2],
       [1, 1, '2', ..., 360.0, 1.0, 2],
       [0, 0, '0', ..., 360.0, 0.0, 1]], dtype=object)

In [22]:
onehotencoder = OneHotEncoder()
temp_col = onehotencoder.fit_transform(x[:,10:]).toarray()

C:\Users\Bala\Python\Anaconda3\envs\playground\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [25]:
temp_col

array([[0., 0.],
       [1., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [0., 1.]])

In [24]:
temp_col = temp_col[:,:-1]

In [26]:
x = x[:,:-1]
x = np.concatenate([x,temp_col], axis = 1) 

In [27]:
df_train.dtypes

Gender                 int32
Married                int32
Dependents            object
Education              int32
Self_Employed          int32
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area          int32
Loan_Status           object
dtype: object

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [27]:
x.shape

(614, 13)

In [29]:
x_train = x[:400,:]
y_train = y[0:400]
x_test = x[400:,:]
y_test = y[400:]

In [30]:
x_train.shape

(400, 12)

In [31]:
x_test.shape

(214, 12)

In [32]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf', random_state=0)
classifier.fit(x_train,y_train)

C:\Users\Bala\Python\Anaconda3\envs\playground\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=0,
    shrinking=True, tol=0.001, verbose=False)

In [33]:
y_pred = classifier.predict(x_test)

In [34]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [35]:
cm

array([[ 34,  36],
       [  4, 140]], dtype=int64)

In [36]:
from sklearn.model_selection import GridSearchCV
#help(GridSearchCV)
parameters = [{'C':[1,10,100,1000], 'kernel' : ['linear']},
             {'C':[1,10,100,1000], 'kernel' : ['rbf'], 'gamma' : [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                          param_grid = parameters,
                          scoring = 'accuracy',
                          cv = 10,
                          n_jobs = -1)
grid_search = grid_search.fit(x_train, y_train)
print(grid_search.best_score_)
print(grid_search.best_params_)
print(grid_search.best_estimator_)


0.8025
{'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}
SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)


C:\Users\Bala\Python\Anaconda3\envs\playground\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [37]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=7, metric='minkowski',n_jobs=-1)
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[ 32  38]
 [ 11 133]]


In [38]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[ 39  31]
 [  8 136]]


In [39]:
(35+141)/(35+35+3+141)

0.822429906542056

In [40]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf', random_state=0)
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[ 34  36]
 [  4 140]]


C:\Users\Bala\Python\Anaconda3\envs\playground\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [41]:
from sklearn.model_selection import cross_val_score
#help(cross_val_score)
accuracies = cross_val_score(estimator = classifier, X = x_train, y = y_train, cv = 10)
accuracies.mean()

C:\Users\Bala\Python\Anaconda3\envs\playground\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Bala\Python\Anaconda3\envs\playground\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Bala\Python\Anaconda3\envs\playground\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Bala

0.8025171982489055

In [42]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)
print((cm[0,0] + cm[1,1]) /np.sum(cm))

[[ 35  35]
 [  3 141]]
0.822429906542056


C:\Users\Bala\Python\Anaconda3\envs\playground\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [43]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=150,criterion='entropy',random_state=0)
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)
print((cm[0,0] + cm[1,1]) /np.sum(cm))

[[ 37  33]
 [ 14 130]]
0.780373831775701


In [44]:
from sklearn.model_selection import GridSearchCV
#help(GridSearchCV)
parameters = [{'n_estimators':[10,100,150,250,500,700], 'criterion' : ['gini'],
                'max_features':['auto', 'sqrt', 'log2'], 'bootstrap':['True','False'],
                 'warm_start':['True','False']},
             {'n_estimators':[10,100,150,250,500,700], 'criterion' : ['entropy'],
             'max_features':['auto', 'sqrt', 'log2'], 'bootstrap':['True','False'],
                 'warm_start':['True','False']}]
grid_search = GridSearchCV(estimator = classifier,
                          param_grid = parameters,
                          scoring = 'accuracy',
                          cv = 10,
                          n_jobs = -1)
grid_search = grid_search.fit(x_train, y_train)
print(grid_search.best_score_)
print(grid_search.best_params_)
print(grid_search.best_estimator_)

0.795
{'bootstrap': 'True', 'criterion': 'entropy', 'max_features': 'auto', 'n_estimators': 100, 'warm_start': 'True'}
RandomForestClassifier(bootstrap='True', class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start='True')


C:\Users\Bala\Python\Anaconda3\envs\playground\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [74]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100,criterion='entropy',max_features='auto',
                                    bootstrap='True',warm_start='True',random_state=0)
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)
print((cm[0,0] + cm[1,1]) /np.sum(cm))

[[ 39  31]
 [ 13 131]]
0.794392523364486


In [47]:
x.shape

(614, 12)

In [48]:
y.shape

(614,)

In [97]:
df_test.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [100]:
from sklearn_pandas import CategoricalImputer
imputer =CategoricalImputer()
df_test['Gender'] = imputer.fit_transform(df_test['Gender'])
df_test['Dependents'] = imputer.fit_transform(df_test['Dependents'])
df_test['Self_Employed'] = imputer.fit_transform(df_test['Self_Employed'])
df_test['Credit_History'] = imputer.fit_transform(df_test['Credit_History'])
df_test['LoanAmount'] = imputer.fit_transform(df_test['LoanAmount'])
df_test['Loan_Amount_Term'] = imputer.fit_transform(df_test['Loan_Amount_Term'])
print(df_test)

      Loan_ID Gender Married Dependents     Education Self_Employed  \
0    LP001015   Male     Yes          0      Graduate            No   
1    LP001022   Male     Yes          1      Graduate            No   
2    LP001031   Male     Yes          2      Graduate            No   
3    LP001035   Male     Yes          2      Graduate            No   
4    LP001051   Male      No          0  Not Graduate            No   
..        ...    ...     ...        ...           ...           ...   
362  LP002971   Male     Yes         3+  Not Graduate           Yes   
363  LP002975   Male     Yes          0      Graduate            No   
364  LP002980   Male      No          0      Graduate            No   
365  LP002986   Male     Yes          0      Graduate            No   
366  LP002989   Male      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5720                  0       110.0             360.0   
1

In [101]:
df_test.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [102]:
df_test.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             1.0         Urban  
4             1.0         Urban

In [103]:
MultiLabelEncoder(['Gender','Married', 'Education', 'Self_Employed', 'Property_Area'], df_test)

In [104]:
df_test

Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
0    LP001015       1        1          0          0              0   
1    LP001022       1        1          1          0              0   
2    LP001031       1        1          2          0              0   
3    LP001035       1        1          2          0              0   
4    LP001051       1        0          0          1              0   
..        ...     ...      ...        ...        ...            ...   
362  LP002971       1        1         3+          1              1   
363  LP002975       1        1          0          0              0   
364  LP002980       1        0          0          0              0   
365  LP002986       1        1          0          0              0   
366  LP002989       1        0          0          0              1   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5720                  0       110.0             360.0   
1               3076               1500       126.0             360.0   
2               5000               1800       208.0             360.0   
3               2340               2546       100.0             360.0   
4               3276                  0        78.0             360.0   
..               ...                ...         ...               ...   
362             4009               1777       113.0             360.0   
363             4158                709       115.0             360.0   
364             3250               1993       126.0             360.0   
365             5000               2393       158.0             360.0   
366             9200                  0        98.0             180.0   

     Credit_History  Property_Area  
0               1.0              2  
1               1.0              2  
2               1.0              2  
3               1.0              2  
4               1.0              2  
..              ...            ...  
362             1.0              2  
363             1.0              2  
364             1.0              1  
365             1.0              0  
366             1.0              0  

[367 rows x 12 columns]

In [105]:
df_test.Property_Area.unique()

array([2, 1, 0], dtype=int64)

In [106]:
df_test.Dependents.unique()

array(['0', '1', '2', '3+'], dtype=object)

In [107]:
df_test.Dependents = df_test.Dependents.replace({"3+": "3"})

In [108]:
df_test = df_test.drop(columns='Loan_ID')

In [109]:
x_actual = df_test.iloc[:,:].values

In [110]:
x_actual.shape

(367, 11)

In [111]:
onehotencoder = OneHotEncoder()
temp_col = onehotencoder.fit_transform(x_actual[:,10:]).toarray()

C:\Users\Bala\Python\Anaconda3\envs\playground\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [112]:
temp_col

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [113]:
temp_col = temp_col[:,:-1]

In [114]:
x_actual = x_actual[:,:-1]
x_actual = np.concatenate([x_actual,temp_col], axis = 1) 

In [115]:
df_test.dtypes

Gender                 int32
Married                int32
Dependents            object
Education              int32
Self_Employed          int32
ApplicantIncome        int64
CoapplicantIncome      int64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area          int32
dtype: object

In [116]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [118]:
x_actual.shape

(367, 12)

In [119]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(x,y)
y_actual = classifier.predict(x_actual)


C:\Users\Bala\Python\Anaconda3\envs\playground\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [121]:
loan_prediction = pd.DataFrame(y_actual)
final = pd.concat([sample['Loan_ID'],loan_prediction],axis=1)

In [122]:
final.columns=['Loan_ID','Loan_Status']
final.to_csv('files/Analytics Vidya/Loan Prediction/submission2.csv', index=False)

In [123]:
actual = pd.read_csv('files/Analytics Vidya/Loan Prediction/submission2.csv')

In [124]:
actual

Loan_ID Loan_Status
0    LP001015           Y
1    LP001022           N
2    LP001031           N
3    LP001035           N
4    LP001051           Y
..        ...         ...
362  LP002971           N
363  LP002975           Y
364  LP002980           N
365  LP002986           N
366  LP002989           Y

[367 rows x 2 columns]