In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import time
from datetime import datetime
%matplotlib inline

In [2]:
df_items = pd.read_csv('.\\files\\Kaggle Competition\\Sale Prediction\\items.csv')
df_categories = pd.read_csv('.\\files\\Kaggle Competition\\Sale Prediction\\item_categories.csv')
df_shops = pd.read_csv('.\\files\\Kaggle Competition\\Sale Prediction\\shops.csv')
df_train = pd.read_csv('.\\files\\Kaggle Competition\\Sale Prediction\\sales_train_v2.csv')
df_test = pd.read_csv('.\\files\\Kaggle Competition\\Sale Prediction\\test.csv') 
df_sample = pd.read_csv('.\\files\\Kaggle Competition\\Sale Prediction\\sample_submission.csv') 

In [3]:
print('Items:\n\n',df_items.head())
print('\n\nitem_categories:\n\n',df_categories.head())
print('\n\nshops:\n\n',df_shops.head())
print('\n\nsales_train_v2:\n\n',df_train.head())
print('\n\ntest:\n\n',df_test.head())

Items:

                                            item_name  item_id  \
0          ! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.)         D        0   
1  !ABBYY FineReader 12 Professional Edition Full...        1   
2      ***В ЛУЧАХ СЛАВЫ   (UNV)                    D        2   
3    ***ГОЛУБАЯ ВОЛНА  (Univ)                      D        3   
4        ***КОРОБКА (СТЕКЛО)                       D        4   

   item_category_id  
0                40  
1                76  
2                40  
3                40  
4                40  


item_categories:

         item_category_name  item_category_id
0  PC - Гарнитуры/Наушники                 0
1         Аксессуары - PS2                 1
2         Аксессуары - PS3                 2
3         Аксессуары - PS4                 3
4         Аксессуары - PSP                 4


shops:

                         shop_name  shop_id
0   !Якутск Орджоникидзе, 56 фран        0
1   !Якутск ТЦ "Центральный" фран        1
2                Адыгея ТЦ "Мега"    

In [4]:
df_train['shop_id'].sort_values().unique()
df_train.shape
# print('Items:\n\n',df_items.dtypes)
# print('\n\nitem_categories:\n\n',df_categories.dtypes)
# print('\n\nshops:\n\n',df_shops.dtypes)
# print('\n\nsales_train_v2:\n\n',df_train.dtypes)
# print('\n\ntest:\n\n',df_test.dtypes)

(2935849, 6)

In [5]:
# print('Items:\n\n',df_items.shape)
# print('\n\nitem_categories:\n\n',df_categories.shape)
# print('\n\nshops:\n\n',df_shops.shape)
# print('\n\nsales_train_v2:\n\n',df_train.shape)
# print('\n\ntest:\n\n',df_test.shape)

In [6]:
# print('Items:\n\n',df_items.isnull().sum())
# print('\n\nitem_categories:\n\n',df_categories.isnull().sum())
# print('\n\nshops:\n\n',df_shops.isnull().sum())
# print('\n\nsales_train_v2:\n\n',df_train.isnull().sum())
# print('\n\ntest:\n\n',df_test.isnull().sum())

In [7]:
# df_train['item_cnt_day'].unique()

In [8]:
df_sample.head()

ID  item_cnt_month
0   0             0.5
1   1             0.5
2   2             0.5
3   3             0.5
4   4             0.5

In [9]:
df_train.drop_duplicates(keep=False, inplace=True)
df_train.shape

(2935837, 6)

In [10]:
df_altered = df_train.copy()
df_altered

date  date_block_num  shop_id  item_id  item_price  \
0        02.01.2013               0       59    22154      999.00   
1        03.01.2013               0       25     2552      899.00   
2        05.01.2013               0       25     2552      899.00   
3        06.01.2013               0       25     2554     1709.05   
4        15.01.2013               0       25     2555     1099.00   
...             ...             ...      ...      ...         ...   
2935844  10.10.2015              33       25     7409      299.00   
2935845  09.10.2015              33       25     7460      299.00   
2935846  14.10.2015              33       25     7459      349.00   
2935847  22.10.2015              33       25     7440      299.00   
2935848  03.10.2015              33       25     7460      299.00   

         item_cnt_day  
0                 1.0  
1                 1.0  
2                -1.0  
3                 1.0  
4                 1.0  
...               ...  
2935844           1.0  
2935845           1.0  
2935846           1.0  
2935847           1.0  
2935848           1.0  

[2935837 rows x 6 columns]

In [11]:
start = datetime.now()
df_altered.date = pd.to_datetime(df_altered.date)
end = datetime.now()
print(end - start)

0:00:00.340077


In [12]:
df_altered.head()

date  date_block_num  shop_id  item_id  item_price  item_cnt_day
0 2013-02-01               0       59    22154      999.00           1.0
1 2013-03-01               0       25     2552      899.00           1.0
2 2013-05-01               0       25     2552      899.00          -1.0
3 2013-06-01               0       25     2554     1709.05           1.0
4 2013-01-15               0       25     2555     1099.00           1.0

In [13]:
df_month = df_altered.groupby([df_altered['date'].dt.strftime('%B'),
                              'shop_id',
                              'item_id','item_price'],as_index=False).agg({'item_cnt_day':'sum'})


In [14]:
#df_month = df_month.sort_values('date')

In [15]:
df_month = df_month.rename(columns={'item_cnt_day':'item_cnt_month'})


In [16]:
print(df_month.shape)
df_month.drop_duplicates(keep=False, inplace=True)
df_month.shape

(1834855, 4)


(671763, 4)

In [17]:
# x_train = df_month.iloc[:,:2].values
# y_train = df_month.iloc[:,-1].values
# from sklearn.ensemble import RandomForestRegressor
# regressor = RandomForestRegressor(n_estimators=100, random_state=0, n_jobs=-1)
# regressor.fit(x_train, y_train)

In [18]:
df_month

shop_id  item_id  item_price  item_cnt_month
3              0      282       109.0             1.0
5              0      783        71.0             1.0
11             0     1018       176.0             1.0
12             0     1067       263.0             2.0
14             0     1332       259.0             1.0
...          ...      ...         ...             ...
1834844       59    22088        79.0            11.0
1834846       59    22091       109.0             4.0
1834847       59    22091       179.0             2.0
1834848       59    22092       109.0            10.0
1834850       59    22114        28.0             1.0

[671763 rows x 4 columns]

In [19]:
x = df_month.iloc[:,:2].values
y = df_month.iloc[:,-1].values

In [20]:
x

array([[    0,   282],
       [    0,   783],
       [    0,  1018],
       ...,
       [   59, 22091],
       [   59, 22092],
       [   59, 22114]], dtype=int64)

In [21]:
from sklearn.model_selection import train_test_split
x_tr,x_te,y_tr,y_te = train_test_split(x, y, test_size=0.2)

In [22]:
# start = datetime.now()
# from sklearn.ensemble import RandomForestRegressor
# regressor = RandomForestRegressor(n_estimators=150, random_state=0, n_jobs=-1)
# regressor.fit(x_tr, y_tr)
# end = datetime.now()
# print(end - start)

In [23]:
# y_pr = regressor.predict(x_te)

In [24]:
# regressor.score(x_te,y_te)

In [25]:
from sklearn.metrics import mean_squared_error as mse
from math import sqrt
def mse(actual, predicted):
    error = sqrt(mse(actual, predicted))
    print(error)
    return error
    

In [26]:
# regressor.fit(x,y)
# cnt_month = regressor.predict(df_test.iloc[:,1:].values)

In [27]:
# cnt_month
# df_sub =  pd.read_csv('.\\files\\Kaggle Competition\\Sale Prediction\\sample_submission.csv') 

In [28]:
# y_prediction = pd.DataFrame(cnt_month)
# dataset = pd.concat([df_sample['ID'], y_prediction], axis=1)
# dataset.columns=['ID','item_cnt_month']
# dataset.to_csv('.\\files\\Kaggle Competition\\Sale Prediction\\submission2.csv', index=False)

In [29]:
# actual = pd.read_csv('.\\files\\Kaggle Competition\\Sale Prediction\\submission2.csv')

# actual

# Artificial Neural Network

In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

C:\Users\Bala\Python\Anaconda3\envs\playground\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [31]:
import tensorflow as tf
tf.test.is_gpu_available()


True

In [32]:
x = x.reshape(-1,2)
x_tr = x_tr.reshape(-1,2)
x_te = x_te.reshape(-1,2)
y = y.reshape(-1,1)
y_tr = y_tr.reshape(-1,1)
y_te = y_te.reshape(-1,1)

In [33]:
x_tr

array([[   19,  6422],
       [   45, 13124],
       [    5, 21441],
       ...,
       [   18,  3438],
       [   30,  4470],
       [   52, 18721]], dtype=int64)

In [34]:
# from sklearn.preprocessing import StandardScaler
# sc_x = StandardScaler()
# sc_y = StandardScaler()
from sklearn.preprocessing import MinMaxScaler
sc_x = MinMaxScaler(feature_range=(0,1))
sc_y = MinMaxScaler(feature_range=(0,1))

In [35]:
x = sc_x.fit_transform(x)
x_tr = sc_x.transform(x_tr)
x_te = sc_x.transform(x_te)
y = sc_y.fit_transform(y)
y_tr = sc_y.transform(y_tr)
y_te = sc_y.transform(y_te)

In [36]:
y

array([[0.00929293],
       [0.00929293],
       [0.00929293],
       ...,
       [0.00969697],
       [0.01292929],
       [0.00929293]])

In [37]:
ann_regressor = Sequential()

In [38]:
ann_regressor.add(Dense(units = 32, activation = 'relu', kernel_initializer = 'normal', input_dim = 2))

In [39]:
ann_regressor.add(Dense(units = 64, activation = 'relu', kernel_initializer = 'normal'))
ann_regressor.add(Dense(units = 64, activation = 'relu', kernel_initializer = 'normal'))
ann_regressor.add(Dense(units = 64, activation = 'relu', kernel_initializer = 'normal'))

In [40]:
ann_regressor.add(Dense(units = 1, kernel_initializer = 'normal', activation = 'linear'))

In [41]:
ann_regressor.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_squared_error'])

In [42]:
ann_regressor.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                96        
_________________________________________________________________
dense_1 (Dense)              (None, 64)                2112      
_________________________________________________________________
dense_2 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_3 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 65        
Total params: 10,593
Trainable params: 10,593
Non-trainable params: 0
_________________________________________________________________


In [43]:
start = datetime.now()
ann_regressor.fit(x_tr, y_tr, batch_size=10, epochs=1)
end = datetime.now()
print(end - start)

Train on 537410 samples
537410/537410 [==============================] - 175s 325us/sample - loss: 4.0809e-05 - mean_squared_error: 4.0809e-05
0:02:54.933684


In [44]:
# from tensorflow.keras import backend as K

# K.clear_session()
# K.reset_uids()

In [45]:
y_pr = ann_regressor.predict(x_te)

In [46]:
y_pr

array([[0.00854946],
       [0.00854946],
       [0.00854946],
       ...,
       [0.00854946],
       [0.00854946],
       [0.00854946]], dtype=float32)

In [47]:
y_pr = sc_y.inverse_transform(y_pr)
y_te = sc_y.inverse_transform(y_te)

In [48]:
y_pr

array([[-0.8400883],
       [-0.8400883],
       [-0.8400883],
       ...,
       [-0.8400883],
       [-0.8400883],
       [-0.8400883]], dtype=float32)

In [49]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_te, y_pr)

ValueError: continuous is not supported

In [50]:
start = datetime.now()
ann_regressor.fit(x_te, y_te, batch_size=10, epochs=10)
end = datetime.now()
print(end - start)

Train on 134353 samples
Epoch 1/10
134353/134353 [==============================] - 55s 411us/sample - loss: 180.5797 - mean_squared_error: 180.5797
Epoch 2/10
134353/134353 [==============================] - 54s 406us/sample - loss: 179.8267 - mean_squared_error: 179.8266
Epoch 3/10
134353/134353 [==============================] - 52s 388us/sample - loss: 179.8220 - mean_squared_error: 179.8212
Epoch 4/10
134353/134353 [==============================] - 53s 396us/sample - loss: 179.8216 - mean_squared_error: 179.8218
Epoch 5/10
134353/134353 [==============================] - 53s 397us/sample - loss: 179.8228 - mean_squared_error: 179.8224
Epoch 6/10
134353/134353 [==============================] - 53s 393us/sample - loss: 179.8226 - mean_squared_error: 179.8221
Epoch 7/10
134353/134353 [==============================] - 55s 413us/sample - loss: 179.8233 - mean_squared_error: 179.8237
Epoch 8/10
134353/134353 [==============================] - 55s 407us/sample - loss: 179.8233 - mean_

In [51]:
y_pr = ann_regressor.predict(x_te)

In [52]:
y_pr = sc_y.inverse_transform(y_pr)

In [54]:
y_pr

array([[6988.8],
       [6988.8],
       [6988.8],
       ...,
       [6988.8],
       [6988.8],
       [6988.8]], dtype=float32)

In [53]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_te, y_pr)

ValueError: continuous is not supported